name: Check My Files

on: [push] # Runs every time you push code

jobs:
  list-files:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4 # This downloads your code to the runner

      - name: View my files
        run: |
          pwd
          ls -la
